#!/usr/bin/env bash
# Bumps versionName/versionCode everywhere and builds the Android app.
#
# Usage:
#   scripts/build-android.sh <versionName> <versionCode> [dev|prod|both]
#
# Examples:
#   scripts/build-android.sh 0.1.4 6            # builds both
#   scripts/build-android.sh 0.1.4 6 dev        # single-ABI (arm64-v8a) release APK for local testing
#   scripts/build-android.sh 0.1.4 6 prod       # full-ABI AAB for Play Store
#
# "dev"  -> android/app/build/outputs/apk/release/app-release.apk    (arm64-v8a only)
# "prod" -> android/app/build/outputs/bundle/release/app-release.aab (all ABIs, for Play's per-device delivery)

set -euo pipefail

VERSION_NAME="${1:?Usage: $0 <versionName> <versionCode> [dev|prod|both]}"
VERSION_CODE="${2:?Usage: $0 <versionName> <versionCode> [dev|prod|both]}"
TARGET="${3:-both}"

if ! [[ "$VERSION_CODE" =~ ^[0-9]+$ ]]; then
  echo "error: versionCode must be a positive integer, got '$VERSION_CODE'" >&2
  exit 1
fi
case "$TARGET" in
  dev|prod|both) ;;
  *) echo "error: target must be dev, prod, or both, got '$TARGET'" >&2; exit 1 ;;
esac

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

if [ ! -d android ]; then
  echo "error: android/ doesn't exist. Run 'npx expo prebuild -p android' first." >&2
  exit 1
fi

# android/ is gitignored (regenerated by `expo prebuild`) so this signing setup is
# ephemeral — if it's missing, prebuild --clean wiped it and it must be reapplied
# by hand before this script can produce a signed build. See maestro-mobile's
# mobile-android-production-build project memory for the full manual steps.
if ! grep -q "MAESTRO_UPLOAD_STORE_FILE" android/gradle.properties 2>/dev/null; then
  echo "error: release signing config missing from android/gradle.properties." >&2
  echo "       android/ was likely regenerated by 'expo prebuild --clean'; reapply the" >&2
  echo "       MAESTRO_UPLOAD_* properties and signingConfigs.release block first." >&2
  exit 1
fi
if [ ! -f credentials/maestro-release.jks ]; then
  echo "error: credentials/maestro-release.jks not found — can't sign a release build." >&2
  exit 1
fi

echo "== Bumping version to versionName=$VERSION_NAME versionCode=$VERSION_CODE =="

# app.json (Expo's source of truth for the display version)
node -e "
const fs = require('fs');
const path = 'app.json';
const j = JSON.parse(fs.readFileSync(path, 'utf8'));
j.expo.version = '$VERSION_NAME';
fs.writeFileSync(path, JSON.stringify(j, null, 2) + '\n');
"

# android/app/build.gradle (regenerated by prebuild, but we edit the live copy so
# the build we're about to run picks it up immediately)
sed -i '' -E "s/versionCode [0-9]+/versionCode $VERSION_CODE/" android/app/build.gradle
sed -i '' -E "s/versionName \"[^\"]*\"/versionName \"$VERSION_NAME\"/" android/app/build.gradle

echo "  app.json:              expo.version = $VERSION_NAME"
echo "  android/app/build.gradle: versionCode=$VERSION_CODE versionName=$VERSION_NAME"

mkdir -p dist
BUILD_TAG="v${VERSION_NAME}-${VERSION_CODE}"

build_dev() {
  echo "== Building dev APK (arm64-v8a only) =="
  (cd android && ./gradlew assembleRelease -PreactNativeArchitectures=arm64-v8a)
  local src="android/app/build/outputs/apk/release/app-release.apk"
  local dest="dist/maestro-${BUILD_TAG}-dev-arm64.apk"
  cp "$src" "$dest"
  echo "  -> $dest ($(du -h "$dest" | cut -f1))"
}

build_prod() {
  echo "== Building prod AAB (all ABIs) =="
  (cd android && ./gradlew bundleRelease)
  local src="android/app/build/outputs/bundle/release/app-release.aab"
  local dest="dist/maestro-${BUILD_TAG}-prod.aab"
  cp "$src" "$dest"
  echo "  -> $dest ($(du -h "$dest" | cut -f1))"
}

case "$TARGET" in
  dev) build_dev ;;
  prod) build_prod ;;
  both) build_dev; build_prod ;;
esac

echo "== Done =="
ls -lh dist/*"${BUILD_TAG}"* 2>/dev/null
